### ISSUE TITLE
Under windows, the compilation fails. Can you get a Windows version?

### ISSUE THREAD

**Issue by xiaoniu1235** [aphenriques/integral#13]
I use vs2017 to compile integrated, but it can't be compiled. Because a lot of templates are used, I can't locate the problem. Can you make a version under windows?

**Comment by aphenriques** [comment]
Hi @xiaoniu1235,

I will probably have access to a Windows machine with Visual Studio soon. I plan to test the library and make it compatible with Visual Studio.

I let you know about it in this issue.

**Comment by aphenriques** [comment]
Hi @xiaoniu1235,

I made the library compatible with Visual Studio Community 2019 Version 16.8.4 (it compiles and passes the test, which is fairly complete). Maybe it won't work with previous versions of Visual Studio. Let me know if you find any issue.
