### ISSUE TITLE
lua_pushglobaltable not supported by Lua 5.1 and LuaJIT

### ISSUE THREAD

**Issue by bverhagen** [aphenriques/integral#3]
Hi,

On your README, you claim that integral is compatible with Lua 5.1 and LuaJIT. Unfortunately, GlobalReference.hpp uses the `lua_pushglobaltable()` function, which was introduced in Lua 5.2 (LuaJIT is currently compatible with Lua 5.1).

Full compiler error:
```
g++ -g -O0 -std=c++17 -o test test.cpp -I ~/integral/install/include -I ~/luajit-2.0/install/include/luajit-2.0 ~/integral/install/lib/libintegral.a ~/luajit-2.0/install/lib/libluajit-5.1.a -ldl

In file included from ~/integral/install/include/integral/StateView.hpp:34,
                 from ~/integral/install/include/integral/State.hpp:29,
                 from ~/integral/install/include/integral/integral.hpp:32,
                 from test.cpp:1:
~/integral/install/include/integral/GlobalReference.hpp: In member function ‘void integral::detail::GlobalReference::push() const’:
~/integral/install/include/integral/GlobalReference.hpp:59:13: error: ‘lua_pushglobaltable’ was not declared in this scope
   59 |             lua_pushglobaltable(getLuaState());
      |
```

Let me know if you need more specific sources, but I think compiling and linking with the latest stable LuaJIT should reproduce the problem.

Refer to the lua manuals for more information on lua_pushglobaltable:
[https://www.lua.org/manual/5.1/](https://www.lua.org/manual/5.1/)
[https://www.lua.org/manual/5.2/](https://www.lua.org/manual/5.2/)

**Comment by aphenriques** [comment]
Hi @bverhagen,

I fixed the problem on c021fe445a8eec7f446daaa3ae1e1b69c9bdbb16. I also put some comments on common.mk that might help anyone building integral with LuaJIT.

Thanks a lot for reporting it! A was already forgetting about LuaJIT and it may be quite useful in another project I am working on now.

Please, let me know if you find any other issue.

**Comment by bverhagen** [comment]
Hi @aphenriques,

It took me some time to get it right with your LuaJIT changes (among other things, I had to change the include path for LuaJIT to `/usr/include/luajit-2.0`, as my distro has a luajit package.

I can now confirm that compiling and linking with luajit works!

**Comment by aphenriques** [comment]
Nice!
